/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef FOURHOPS_H
#define FOURHOPS_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace fourhops {

class Fourhops : public RapidNetApplicationBase
{
public:
  static const string FOURHOPS;
  static const string LINK;
  static const string ONEHOP;
  static const string R2LOCAL1R2ONEHOPMIDSEND;
  static const string R2LOCAL2TWOHOPSSEND;
  static const string R2ONEHOPMID;
  static const string R2ONEHOPMIDDELETE;
  static const string R3LOCAL1R3LINKMIDSEND;
  static const string R3LOCAL2TWOHOPSSEND;
  static const string R3LINKMID;
  static const string R3LINKMIDDELETE;
  static const string R5LOCAL1R5ONEHOPMIDSEND;
  static const string R5LOCAL2THREEHOPSSEND;
  static const string R5ONEHOPMID;
  static const string R5ONEHOPMIDDELETE;
  static const string R6LOCAL1R6TWOHOPS1MIDSEND;
  static const string R6TWOHOPS1MID;
  static const string R6TWOHOPS1MIDDELETE;
  static const string R7LOCAL1R7ONEHOPMIDSEND;
  static const string R7ONEHOPMID;
  static const string R7ONEHOPMIDDELETE;
  static const string THREEHOPS;
  static const string THREEHOPSDELETE;
  static const string TWOHOPS;
  static const string TWOHOPS1;
  static const string TWOHOPSDELETE;

  static TypeId GetTypeId (void);

  Fourhops ();

  virtual ~Fourhops ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0Ins (Ptr<Tuple> link);

  virtual void R1Eca0Del (Ptr<Tuple> link);

  virtual void R2Local1Eca0RemoteIns (Ptr<Tuple> r2Local1r2onehopMidsend);

  virtual void R2Local1Eca0RemoteDel (Ptr<Tuple> r2onehopMidDelete);

  virtual void R2Local1Eca0Ins (Ptr<Tuple> onehop);

  virtual void R2Local1Eca0Del (Ptr<Tuple> onehop);

  virtual void R2Local2Eca0RemoteIns (Ptr<Tuple> r2Local2twohopssend);

  virtual void R2Local2Eca0RemoteDel (Ptr<Tuple> twohopsDelete);

  virtual void R2Local2Eca0Ins (Ptr<Tuple> r2onehopMid);

  virtual void R2Local2Eca0Del (Ptr<Tuple> r2onehopMid);

  virtual void R2Local2Eca1Ins (Ptr<Tuple> link);

  virtual void R2Local2Eca1Del (Ptr<Tuple> link);

  virtual void R3Local1Eca0RemoteIns (Ptr<Tuple> r3Local1r3linkMidsend);

  virtual void R3Local1Eca0RemoteDel (Ptr<Tuple> r3linkMidDelete);

  virtual void R3Local1Eca0Ins (Ptr<Tuple> link);

  virtual void R3Local1Eca0Del (Ptr<Tuple> link);

  virtual void R3Local2Eca0RemoteIns (Ptr<Tuple> r3Local2twohopssend);

  virtual void R3Local2Eca0Ins (Ptr<Tuple> r3linkMid);

  virtual void R3Local2Eca0Del (Ptr<Tuple> r3linkMid);

  virtual void R3Local2Eca1Ins (Ptr<Tuple> onehop);

  virtual void R3Local2Eca1Del (Ptr<Tuple> onehop);

  virtual void R4Eca0Ins (Ptr<Tuple> twohops);

  virtual void R4Eca0Del (Ptr<Tuple> twohops);

  virtual void R5Local1Eca0RemoteIns (Ptr<Tuple> r5Local1r5onehopMidsend);

  virtual void R5Local1Eca0RemoteDel (Ptr<Tuple> r5onehopMidDelete);

  virtual void R5Local1Eca0Ins (Ptr<Tuple> onehop);

  virtual void R5Local1Eca0Del (Ptr<Tuple> onehop);

  virtual void R5Local2Eca0RemoteIns (Ptr<Tuple> r5Local2threehopssend);

  virtual void R5Local2Eca0RemoteDel (Ptr<Tuple> threehopsDelete);

  virtual void R5Local2Eca0Ins (Ptr<Tuple> r5onehopMid);

  virtual void R5Local2Eca0Del (Ptr<Tuple> r5onehopMid);

  virtual void R5Local2Eca1Ins (Ptr<Tuple> twohops);

  virtual void R5Local2Eca1Del (Ptr<Tuple> twohops);

  virtual void R6Local1Eca0RemoteIns (Ptr<Tuple> r6Local1r6twohops1Midsend);

  virtual void R6Local1Eca0RemoteDel (Ptr<Tuple> r6twohops1MidDelete);

  virtual void R6Local1Eca0Ins (Ptr<Tuple> twohops1);

  virtual void R6Local1Eca0Del (Ptr<Tuple> twohops1);

  virtual void R6Local2Eca0Ins (Ptr<Tuple> r6twohops1Mid);

  virtual void R6Local2Eca1Ins (Ptr<Tuple> twohops);

  virtual void R7Local1Eca0RemoteIns (Ptr<Tuple> r7Local1r7onehopMidsend);

  virtual void R7Local1Eca0RemoteDel (Ptr<Tuple> r7onehopMidDelete);

  virtual void R7Local1Eca0Ins (Ptr<Tuple> onehop);

  virtual void R7Local1Eca0Del (Ptr<Tuple> onehop);

  virtual void R7Local2Eca0Ins (Ptr<Tuple> r7onehopMid);

  virtual void R7Local2Eca1Ins (Ptr<Tuple> threehops);

};

} // namespace fourhops
} // namespace rapidnet
} // namespace ns3

#endif // FOURHOPS_H
