/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef REACHABLE_H
#define REACHABLE_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace reachable {

class Reachable : public RapidNetApplicationBase
{
public:
  static const string D2LOCAL1D2LINKMIDSEND;
  static const string D2LOCAL2REACHABLESEND;
  static const string D2LINKMID;
  static const string D2LINKMIDDELETE;
  static const string D3LOCAL1D3REACHABLEMIDSEND;
  static const string D3LOCAL2REACHABLESEND;
  static const string D3REACHABLEMID;
  static const string D3REACHABLEMIDDELETE;
  static const string LINK;
  static const string REACHABLE;
  static const string REACHABLEDELETE;

  static TypeId GetTypeId (void);

  Reachable ();

  virtual ~Reachable ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void D1Eca0Ins (Ptr<Tuple> link);

  virtual void D1Eca0Del (Ptr<Tuple> link);

  virtual void D2Local1Eca0RemoteIns (Ptr<Tuple> d2Local1d2linkMidsend);

  virtual void D2Local1Eca0RemoteDel (Ptr<Tuple> d2linkMidDelete);

  virtual void D2Local1Eca0Ins (Ptr<Tuple> link);

  virtual void D2Local1Eca0Del (Ptr<Tuple> link);

  virtual void D2Local2Eca0RemoteIns (Ptr<Tuple> d2Local2reachablesend);

  virtual void D2Local2Eca0RemoteDel (Ptr<Tuple> reachableDelete);

  virtual void D2Local2Eca0Ins (Ptr<Tuple> d2linkMid);

  virtual void D2Local2Eca0Del (Ptr<Tuple> d2linkMid);

  virtual void D2Local2Eca1Ins (Ptr<Tuple> reachable);

  virtual void D2Local2Eca1Del (Ptr<Tuple> reachable);

  virtual void D3Local1Eca0RemoteIns (Ptr<Tuple> d3Local1d3reachableMidsend);

  virtual void D3Local1Eca0RemoteDel (Ptr<Tuple> d3reachableMidDelete);

  virtual void D3Local1Eca0Ins (Ptr<Tuple> reachable);

  virtual void D3Local1Eca0Del (Ptr<Tuple> reachable);

  virtual void D3Local2Eca0RemoteIns (Ptr<Tuple> d3Local2reachablesend);

  virtual void D3Local2Eca0Ins (Ptr<Tuple> d3reachableMid);

  virtual void D3Local2Eca0Del (Ptr<Tuple> d3reachableMid);

  virtual void D3Local2Eca1Ins (Ptr<Tuple> link);

  virtual void D3Local2Eca1Del (Ptr<Tuple> link);

};

} // namespace reachable
} // namespace rapidnet
} // namespace ns3

#endif // REACHABLE_H
