/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef THREEHOPS_H
#define THREEHOPS_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace threehops {

class Threehops : public RapidNetApplicationBase
{
public:
  static const string LINK;
  static const string ONEHOP;
  static const string R2LOCAL1R2LINKMIDSEND;
  static const string R2LOCAL2TWOHOPSSEND;
  static const string R2LINKMID;
  static const string R2LINKMIDDELETE;
  static const string R3LOCAL1R3ONEHOPMIDSEND;
  static const string R3ONEHOPMID;
  static const string R3ONEHOPMIDDELETE;
  static const string R4LOCAL1R4TWOHOPSMIDSEND;
  static const string R4TWOHOPSMID;
  static const string R4TWOHOPSMIDDELETE;
  static const string THREEHOPS;
  static const string TWOHOPS;
  static const string TWOHOPSDELETE;

  static TypeId GetTypeId (void);

  Threehops ();

  virtual ~Threehops ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0Ins (Ptr<Tuple> link);

  virtual void R1Eca0Del (Ptr<Tuple> link);

  virtual void R2Local1Eca0RemoteIns (Ptr<Tuple> r2Local1r2linkMidsend);

  virtual void R2Local1Eca0RemoteDel (Ptr<Tuple> r2linkMidDelete);

  virtual void R2Local1Eca0Ins (Ptr<Tuple> link);

  virtual void R2Local1Eca0Del (Ptr<Tuple> link);

  virtual void R2Local2Eca0RemoteIns (Ptr<Tuple> r2Local2twohopssend);

  virtual void R2Local2Eca0RemoteDel (Ptr<Tuple> twohopsDelete);

  virtual void R2Local2Eca0Ins (Ptr<Tuple> r2linkMid);

  virtual void R2Local2Eca0Del (Ptr<Tuple> r2linkMid);

  virtual void R2Local2Eca1Ins (Ptr<Tuple> onehop);

  virtual void R2Local2Eca1Del (Ptr<Tuple> onehop);

  virtual void R3Local1Eca0RemoteIns (Ptr<Tuple> r3Local1r3onehopMidsend);

  virtual void R3Local1Eca0RemoteDel (Ptr<Tuple> r3onehopMidDelete);

  virtual void R3Local1Eca0Ins (Ptr<Tuple> onehop);

  virtual void R3Local1Eca0Del (Ptr<Tuple> onehop);

  virtual void R3Local2Eca0Ins (Ptr<Tuple> r3onehopMid);

  virtual void R3Local2Eca1Ins (Ptr<Tuple> twohops);

  virtual void R4Local1Eca0RemoteIns (Ptr<Tuple> r4Local1r4twohopsMidsend);

  virtual void R4Local1Eca0RemoteDel (Ptr<Tuple> r4twohopsMidDelete);

  virtual void R4Local1Eca0Ins (Ptr<Tuple> twohops);

  virtual void R4Local1Eca0Del (Ptr<Tuple> twohops);

  virtual void R4Local2Eca0Ins (Ptr<Tuple> r4twohopsMid);

  virtual void R4Local2Eca1Ins (Ptr<Tuple> onehop);

};

} // namespace threehops
} // namespace rapidnet
} // namespace ns3

#endif // THREEHOPS_H
