/* A RapidNet application. Generated by RapidNet compiler. */

#include "twohops.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::twohops;

const string Twohops::LINK = "link";
const string Twohops::ONEHOP = "onehop";
const string Twohops::TWOHOPS = "twohops";

NS_LOG_COMPONENT_DEFINE ("Twohops");
NS_OBJECT_ENSURE_REGISTERED (Twohops);

TypeId
Twohops::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::twohops::Twohops")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<Twohops> ()
    ;
  return tid;
}

Twohops::Twohops()
{
  NS_LOG_FUNCTION_NOARGS ();
}

Twohops::~Twohops()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
Twohops::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
Twohops::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("Twohops Application Started");
}

void
Twohops::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("Twohops Application Stopped");
}

void
Twohops::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (LINK, attrdeflist (
    attrdef ("link_attr1", IPV4),
    attrdef ("link_attr2", IPV4)));

  AddRelationWithKeys (ONEHOP, attrdeflist (
    attrdef ("onehop_attr1", IPV4),
    attrdef ("onehop_attr2", IPV4)));

  AddRelationWithKeys (TWOHOPS, attrdeflist (
    attrdef ("twohops_attr1", IPV4),
    attrdef ("twohops_attr2", IPV4)));

}

void
Twohops::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsInsertEvent (tuple, LINK))
    {
      R1Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, LINK))
    {
      R1Eca0Del (tuple);
    }
  if (IsInsertEvent (tuple, LINK))
    {
      R2Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, LINK))
    {
      R2Eca0Del (tuple);
    }
  if (IsInsertEvent (tuple, ONEHOP))
    {
      R2Eca1Ins (tuple);
    }
  if (IsDeleteEvent (tuple, ONEHOP))
    {
      R2Eca1Del (tuple);
    }
}

void
Twohops::R1Eca0Ins (Ptr<Tuple> link)
{
  RAPIDNET_LOG_INFO ("R1Eca0Ins triggered");

  Ptr<Tuple> result = link;

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("link_attr3"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    ONEHOP,
    strlist ("link_attr1",
      "link_attr2",
      "link_attr3"),
    strlist ("onehop_attr1",
      "onehop_attr2",
      "onehop_attr3"));

  Insert (result);
}

void
Twohops::R1Eca0Del (Ptr<Tuple> link)
{
  RAPIDNET_LOG_INFO ("R1Eca0Del triggered");

  Ptr<Tuple> result = link;

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("link_attr3"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    ONEHOP,
    strlist ("link_attr1",
      "link_attr2",
      "link_attr3"),
    strlist ("onehop_attr1",
      "onehop_attr2",
      "onehop_attr3"));

  Delete (result);
}

void
Twohops::R2Eca0Ins (Ptr<Tuple> link)
{
  RAPIDNET_LOG_INFO ("R2Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (ONEHOP)->Join (
    link,
    strlist ("onehop_attr2", "onehop_attr1"),
    strlist ("link_attr2", "link_attr1"));

  result->Assign (Assignor::New ("Cost",
    Operation::New (RN_PLUS,
      VarExpr::New ("link_attr3"),
      VarExpr::New ("onehop_attr3"))));

  result = result->Project (
    TWOHOPS,
    strlist ("link_attr1",
      "link_attr2",
      "Cost"),
    strlist ("twohops_attr1",
      "twohops_attr2",
      "twohops_attr3"));

  Insert (result);
}

void
Twohops::R2Eca0Del (Ptr<Tuple> link)
{
  RAPIDNET_LOG_INFO ("R2Eca0Del triggered");

  Ptr<RelationBase> result;

  result = GetRelation (ONEHOP)->Join (
    link,
    strlist ("onehop_attr2", "onehop_attr1"),
    strlist ("link_attr2", "link_attr1"));

  result->Assign (Assignor::New ("Cost",
    Operation::New (RN_PLUS,
      VarExpr::New ("link_attr3"),
      VarExpr::New ("onehop_attr3"))));

  result = result->Project (
    TWOHOPS,
    strlist ("link_attr1",
      "link_attr2",
      "Cost"),
    strlist ("twohops_attr1",
      "twohops_attr2",
      "twohops_attr3"));

  Delete (result);
}

void
Twohops::R2Eca1Ins (Ptr<Tuple> onehop)
{
  RAPIDNET_LOG_INFO ("R2Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    onehop,
    strlist ("link_attr2", "link_attr1"),
    strlist ("onehop_attr2", "onehop_attr1"));

  result->Assign (Assignor::New ("Cost",
    Operation::New (RN_PLUS,
      VarExpr::New ("link_attr3"),
      VarExpr::New ("onehop_attr3"))));

  result = result->Project (
    TWOHOPS,
    strlist ("onehop_attr1",
      "onehop_attr2",
      "Cost"),
    strlist ("twohops_attr1",
      "twohops_attr2",
      "twohops_attr3"));

  Insert (result);
}

void
Twohops::R2Eca1Del (Ptr<Tuple> onehop)
{
  RAPIDNET_LOG_INFO ("R2Eca1Del triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    onehop,
    strlist ("link_attr2", "link_attr1"),
    strlist ("onehop_attr2", "onehop_attr1"));

  result->Assign (Assignor::New ("Cost",
    Operation::New (RN_PLUS,
      VarExpr::New ("link_attr3"),
      VarExpr::New ("onehop_attr3"))));

  result = result->Project (
    TWOHOPS,
    strlist ("onehop_attr1",
      "onehop_attr2",
      "Cost"),
    strlist ("twohops_attr1",
      "twohops_attr2",
      "twohops_attr3"));

  Delete (result);
}

